## Write a Numpy program to compute the multiplication of two given matrixes

In [2]:
import numpy as np

In [3]:
A = np.array([
    [1,2],
    [3,4]])

B = np.array([
    [1,2, 3],
    [4,5, 6]])
res=np.dot(A,B)
print(res)

[[ 9 12 15]
 [19 26 33]]


## Write a NumPy program to compute the determinant of a given square array

In [4]:
A = np.array([
    [1,2],
    [3,4]])
res=np.linalg.det(A)
print('The determinant is= ',res)

The determinant is=  -2.0000000000000004


## Write a NumPy program to compute the cross product of two given vectors

In [9]:
A=np.array([1,2,3])
B=np.array([4,5,6])
res=np.cross(A,B)
print("The cross product is ")
print(res)

The cross product is 
[-3  6 -3]


## Write a NumPy program to compute the condition number of a given matrix
the condition number of a function measures how much the output value of the function can change for a small change in the input argument. This is used to measure how sensitive a function is to changes or errors in the input, and how much error in the output results from an error in the input.

*hint: look for something similar in the `linalg` module*

In [6]:
dir(np.linalg)

['LinAlgError',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_umath_linalg',
 'cholesky',
 'cond',
 'det',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'inv',
 'lapack_lite',
 'linalg',
 'lstsq',
 'matrix_power',
 'matrix_rank',
 'multi_dot',
 'norm',
 'pinv',
 'qr',
 'slogdet',
 'solve',
 'svd',
 'tensorinv',
 'tensorsolve',
 'test']

In [8]:
A = np.array([
    [1,2],
    [3,4]])
res=np.linalg.cond(A)
print("The condition number is = ",res)

The condition number is =  14.933034373659265


## Write a NumPy program to compute the inverse of a given matrix

In [10]:
arr = np.array([[1, 2], 
                [3,4]])
  
inverse_array = np.linalg.inv(arr)
print("Inverse array is ")
print(inverse_array)

Inverse array is 
[[-2.   1. ]
 [ 1.5 -0.5]]
